### ISSUE TITLE
Fragen an Nicole

### ISSUE THREAD

**Issue by valopaya** [Frank-Mayer/how-to-science#9]

**Comment by nondrusch** [comment]
Hey ihr... 
Es gibt ein FOrmular von Nadine Klimek, das müsstest ihr ausfüllen und schicken, um im Studium Generale Katalog berücksichtigt zu werden. Sie legt dann den Ilias-Kurs für Euch an. 
ECTS bekommt ihr natürlich alle. Es könnte sein, dass ich dafür formal den Kurs mitdurchführen muss. Da können wir aber klären. Die ECTS-Zahl hängt vom geplanten Aufwand ab. Ihr könnte etwa auch ein Forschungsprojekt vorlagern und hier ein Konzept erarbeiten, auch das kann mit ECTS belegt werden.

**Comment by Frank-Mayer** [comment]
This issue is still open. Please have a look at it. @Frank-Mayer @valopaya

**Comment by Frank-Mayer** [comment]
This issue is still open. Please have a look at it. @Frank-Mayer @valopaya

**Comment by Frank-Mayer** [comment]
This issue is still open. Please have a look at it. @Frank-Mayer @valopaya
